use std::net::SocketAddr;

use rosc::{OscMessage, OscPacket, OscType};
use tokio::net::UdpSocket;
use tokio::sync::mpsc;
use tracing::{info, warn, debug, error};

/// Events generated by the trigger listener for the main loop to process.
#[derive(Debug)]
pub enum TriggerEvent {
    /// Fire a specific cue by number.
    FireCue(f32),
    /// Fire the next cue.
    GoNext,
    /// Go to the previous cue.
    GoPrevious,
    /// Query current cue — reply to the given address.
    QueryCurrent { reply_addr: SocketAddr },
    /// Fire a macro by name or ID (placeholder for Phase 4).
    MacroFire(String),
}

/// Listens on a UDP port for incoming OSC triggers (QLab, external controllers).
pub struct TriggerListener;

impl TriggerListener {
    /// Start the trigger listener on the given address.
    /// Returns a receiver channel for trigger events.
    pub async fn start(
        listen_addr: SocketAddr,
    ) -> std::io::Result<mpsc::Receiver<TriggerEvent>> {
        let socket = UdpSocket::bind(listen_addr).await?;
        let (tx, rx) = mpsc::channel(256);

        info!("QLab trigger listener started on {listen_addr}");
        tokio::spawn(listen_loop(socket, tx));

        Ok(rx)
    }
}

/// Background loop: receive OSC messages and parse them into TriggerEvents.
async fn listen_loop(socket: UdpSocket, tx: mpsc::Sender<TriggerEvent>) {
    let socket = std::sync::Arc::new(socket);
    let mut buf = vec![0u8; 4096];

    loop {
        match socket.recv_from(&mut buf).await {
            Ok((size, src)) => {
                match rosc::decoder::decode_udp(&buf[..size]) {
                    Ok((_, packet)) => {
                        process_trigger_packet(packet, src, &tx, &socket).await;
                    }
                    Err(e) => {
                        warn!("Trigger listener: failed to decode OSC from {src}: {e}");
                    }
                }
            }
            Err(e) => {
                error!("Trigger listener: UDP receive error: {e}");
                break;
            }
        }
    }
}

/// Process an OSC packet into trigger events.
async fn process_trigger_packet(
    packet: OscPacket,
    src: SocketAddr,
    tx: &mpsc::Sender<TriggerEvent>,
    _socket: &std::sync::Arc<UdpSocket>,
) {
    match packet {
        OscPacket::Message(msg) => {
            if let Some(event) = parse_trigger_message(&msg.addr, &msg.args, src) {
                debug!(path = msg.addr, ?event, "Trigger received");
                if tx.send(event).await.is_err() {
                    error!("Trigger event channel closed");
                }
            } else {
                debug!(path = msg.addr, %src, "Unknown trigger message");
            }
        }
        OscPacket::Bundle(bundle) => {
            for p in bundle.content {
                Box::pin(process_trigger_packet(p, src, tx, _socket)).await;
            }
        }
    }
}

/// Parse a trigger OSC message into a TriggerEvent.
fn parse_trigger_message(path: &str, args: &[OscType], src: SocketAddr) -> Option<TriggerEvent> {
    match path {
        "/cue/fire" => {
            // Accept both INT and FLOAT for cue number
            let number = match args.first() {
                Some(OscType::Int(n)) => *n as f32,
                Some(OscType::Float(f)) => *f,
                _ => {
                    warn!("Trigger /cue/fire: missing or invalid cue number argument");
                    return None;
                }
            };
            Some(TriggerEvent::FireCue(number))
        }
        "/cue/go" => Some(TriggerEvent::GoNext),
        "/cue/previous" => Some(TriggerEvent::GoPrevious),
        "/cue/current" => Some(TriggerEvent::QueryCurrent { reply_addr: src }),
        "/macro/fire" => {
            let name = match args.first() {
                Some(OscType::String(s)) => s.clone(),
                Some(OscType::Int(n)) => n.to_string(),
                _ => {
                    warn!("Trigger /macro/fire: missing name or ID argument");
                    return None;
                }
            };
            Some(TriggerEvent::MacroFire(name))
        }
        _ => None,
    }
}

/// Send an OSC reply to the given address (used for /cue/current response).
pub async fn send_reply(
    socket: &UdpSocket,
    dest: SocketAddr,
    path: &str,
    args: Vec<OscType>,
) -> std::io::Result<()> {
    let msg = OscMessage {
        addr: path.to_string(),
        args,
    };
    let packet = OscPacket::Message(msg);
    let buf = rosc::encoder::encode(&packet).map_err(|e| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, format!("OSC encode error: {e}"))
    })?;
    socket.send_to(&buf, dest).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_cue_fire_int() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/fire", &[OscType::Int(5)], src).unwrap();
        match event {
            TriggerEvent::FireCue(n) => assert!((n - 5.0).abs() < 0.001),
            _ => panic!("Expected FireCue"),
        }
    }

    #[test]
    fn parse_cue_fire_float() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/fire", &[OscType::Float(1.5)], src).unwrap();
        match event {
            TriggerEvent::FireCue(n) => assert!((n - 1.5).abs() < 0.001),
            _ => panic!("Expected FireCue"),
        }
    }

    #[test]
    fn parse_cue_go() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/go", &[], src).unwrap();
        assert!(matches!(event, TriggerEvent::GoNext));
    }

    #[test]
    fn parse_cue_previous() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/previous", &[], src).unwrap();
        assert!(matches!(event, TriggerEvent::GoPrevious));
    }

    #[test]
    fn parse_cue_current() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/current", &[], src).unwrap();
        match event {
            TriggerEvent::QueryCurrent { reply_addr } => {
                assert_eq!(reply_addr, src);
            }
            _ => panic!("Expected QueryCurrent"),
        }
    }

    #[test]
    fn parse_macro_fire() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message(
            "/macro/fire",
            &[OscType::String("mute_all".into())],
            src,
        ).unwrap();
        match event {
            TriggerEvent::MacroFire(name) => assert_eq!(name, "mute_all"),
            _ => panic!("Expected MacroFire"),
        }
    }

    #[test]
    fn parse_unknown_returns_none() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        assert!(parse_trigger_message("/unknown/path", &[], src).is_none());
    }
}
