use std::net::SocketAddr;

use rosc::{OscMessage, OscPacket, OscType};
use tokio::net::UdpSocket;
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;
use tracing::{debug, error, info, warn};

use crate::model::cidr::{self, Ipv4Cidr};

/// Events generated by the trigger listener for the main loop to process.
#[derive(Debug)]
pub enum TriggerEvent {
    /// Fire a specific cue by number.
    FireCue(f32),
    /// Fire the next cue.
    GoNext,
    /// Go to the previous cue.
    GoPrevious,
    /// Query current cue — reply to the given address.
    QueryCurrent { reply_addr: SocketAddr },
    /// Fire a macro by name or ID (placeholder for Phase 4).
    MacroFire(String),
    /// Phase E: recall a snapshot directly by name or UUID. Generated by
    /// `/snapshot/recall` and `/snapshot/recall_full`. The
    /// `ignore_scope` flag bypasses the snapshot's exclusion scope (only
    /// meaningful for `SnapshotKind::ApplyOnRecall` snapshots — see
    /// `SnapshotEngine::recall`). The identifier is matched UUID-first,
    /// then case-insensitive name fallback (see `resolve_snapshot`).
    SnapshotRecall {
        identifier: String,
        ignore_scope: bool,
    },
}

/// Listens on a UDP port for incoming OSC triggers (QLab, external controllers).
pub struct TriggerListener;

impl TriggerListener {
    /// Start the trigger listener on the given address.
    /// Returns a receiver channel for trigger events.
    pub async fn start(listen_addr: SocketAddr) -> std::io::Result<mpsc::Receiver<TriggerEvent>> {
        Self::start_with_cancel(listen_addr, CancellationToken::new(), None, Vec::new()).await
    }

    /// Start the trigger listener with a CancellationToken for clean shutdown
    /// and an optional source-IP CIDR allowlist. An empty allowlist accepts
    /// all sources (current behavior); a non-empty list drops packets from
    /// any source not matching at least one CIDR — see audit H5 for the
    /// closed-LAN deployment rationale.
    pub async fn start_with_cancel(
        listen_addr: SocketAddr,
        cancel: CancellationToken,
        interface_name: Option<&str>,
        allowlist: Vec<Ipv4Cidr>,
    ) -> std::io::Result<mpsc::Receiver<TriggerEvent>> {
        let socket =
            crate::ui::net_interfaces::create_bound_udp_socket(listen_addr, interface_name).await?;
        let (tx, rx) = mpsc::channel(256);

        if allowlist.is_empty() {
            info!("QLab trigger listener started on {listen_addr} (no source allowlist)");
        } else {
            info!(
                allowlist_size = allowlist.len(),
                "QLab trigger listener started on {listen_addr} with CIDR allowlist"
            );
        }
        tokio::spawn(listen_loop(socket, tx, cancel, allowlist));

        Ok(rx)
    }
}

/// Background loop: receive OSC messages and parse them into TriggerEvents.
async fn listen_loop(
    socket: UdpSocket,
    tx: mpsc::Sender<TriggerEvent>,
    cancel: CancellationToken,
    allowlist: Vec<Ipv4Cidr>,
) {
    let socket = std::sync::Arc::new(socket);
    let mut buf = vec![0u8; 4096];
    let mut blocked = 0u64;

    loop {
        tokio::select! {
            _ = cancel.cancelled() => {
                info!("Trigger listener cancelled — releasing port");
                break;
            }
            result = socket.recv_from(&mut buf) => {
                match result {
                    Ok((size, src)) => {
                        if !cidr::ip_allowed(src.ip(), &allowlist) {
                            blocked = blocked.saturating_add(1);
                            if blocked.is_power_of_two() {
                                warn!(%src, blocked, "Trigger listener: dropped packet (source not in CIDR allowlist)");
                            }
                            continue;
                        }
                        match rosc::decoder::decode_udp(&buf[..size]) {
                            Ok((_, packet)) => {
                                process_trigger_packet(packet, src, &tx, &socket).await;
                            }
                            Err(e) => {
                                warn!("Trigger listener: failed to decode OSC from {src}: {e}");
                            }
                        }
                    }
                    Err(e) => {
                        error!("Trigger listener: UDP receive error: {e}");
                        break;
                    }
                }
            }
        }
    }
    drop(socket);
}

/// Process an OSC packet into trigger events.
async fn process_trigger_packet(
    packet: OscPacket,
    src: SocketAddr,
    tx: &mpsc::Sender<TriggerEvent>,
    _socket: &std::sync::Arc<UdpSocket>,
) {
    match packet {
        OscPacket::Message(msg) => {
            // QLab cue-creation replies land here (this is the app's
            // QLab-facing port). They carry a `/reply/.../uniqueID` address
            // and a single JSON string arg; route the uid to the in-flight
            // export via the bus instead of treating them as triggers. See
            // `crate::osc::qlab_reply`.
            if msg.addr.contains("uniqueID") {
                if let Some(OscType::String(json)) = msg.args.first() {
                    match crate::osc::qlab_reply::parse_unique_id_reply(json) {
                        Some(uid) => {
                            debug!(path = msg.addr, uid, "QLab uniqueID reply");
                            crate::osc::qlab_reply::global().deliver(uid).await;
                        }
                        None => debug!(path = msg.addr, %src, "QLab reply parse failed"),
                    }
                }
                return;
            }
            if let Some(event) = parse_trigger_message(&msg.addr, &msg.args, src) {
                debug!(path = msg.addr, ?event, "Trigger received");
                if tx.send(event).await.is_err() {
                    error!("Trigger event channel closed");
                }
            } else {
                debug!(path = msg.addr, %src, "Unknown trigger message");
            }
        }
        OscPacket::Bundle(bundle) => {
            for p in bundle.content {
                Box::pin(process_trigger_packet(p, src, tx, _socket)).await;
            }
        }
    }
}

/// Parse a trigger OSC message into a TriggerEvent.
pub(crate) fn parse_trigger_message(
    path: &str,
    args: &[OscType],
    src: SocketAddr,
) -> Option<TriggerEvent> {
    match path {
        "/cue/fire" => {
            // Accept both INT and FLOAT for cue number
            let number = match args.first() {
                Some(OscType::Int(n)) => *n as f32,
                Some(OscType::Float(f)) => *f,
                _ => {
                    warn!("Trigger /cue/fire: missing or invalid cue number argument");
                    return None;
                }
            };
            Some(TriggerEvent::FireCue(number))
        }
        "/cue/go" => Some(TriggerEvent::GoNext),
        "/cue/previous" => Some(TriggerEvent::GoPrevious),
        "/cue/current" => Some(TriggerEvent::QueryCurrent { reply_addr: src }),
        "/macro/fire" => {
            let name = match args.first() {
                Some(OscType::String(s)) => s.clone(),
                Some(OscType::Int(n)) => n.to_string(),
                _ => {
                    warn!("Trigger /macro/fire: missing name or ID argument");
                    return None;
                }
            };
            Some(TriggerEvent::MacroFire(name))
        }
        // Phase E: snapshot recall by name or UUID. The two address forms
        // differ only in `ignore_scope` — `/snapshot/recall_full` bypasses
        // the snapshot's exclusion scope (the Phase B "recall without
        // scope" semantics). Both expect a single string argument.
        crate::osc::SNAPSHOT_RECALL_ADDR => parse_snapshot_recall(args, false),
        crate::osc::SNAPSHOT_RECALL_FULL_ADDR => parse_snapshot_recall(args, true),
        _ => None,
    }
}

/// Shared parser for the two `/snapshot/recall*` address forms.
fn parse_snapshot_recall(args: &[OscType], ignore_scope: bool) -> Option<TriggerEvent> {
    let identifier = match args.first() {
        Some(OscType::String(s)) => s.clone(),
        _ => {
            warn!("Trigger /snapshot/recall: missing or non-string identifier argument");
            return None;
        }
    };
    if identifier.is_empty() {
        warn!("Trigger /snapshot/recall: empty identifier");
        return None;
    }
    Some(TriggerEvent::SnapshotRecall {
        identifier,
        ignore_scope,
    })
}

/// Send an OSC reply to the given address (used for /cue/current response).
pub async fn send_reply(
    socket: &UdpSocket,
    dest: SocketAddr,
    path: &str,
    args: Vec<OscType>,
) -> std::io::Result<()> {
    let msg = OscMessage {
        addr: path.to_string(),
        args,
    };
    let packet = OscPacket::Message(msg);
    let buf = rosc::encoder::encode(&packet).map_err(|e| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("OSC encode error: {e}"),
        )
    })?;
    socket.send_to(&buf, dest).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_cue_fire_int() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/fire", &[OscType::Int(5)], src).unwrap();
        match event {
            TriggerEvent::FireCue(n) => assert!((n - 5.0).abs() < 0.001),
            _ => panic!("Expected FireCue"),
        }
    }

    #[test]
    fn parse_cue_fire_float() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/fire", &[OscType::Float(1.5)], src).unwrap();
        match event {
            TriggerEvent::FireCue(n) => assert!((n - 1.5).abs() < 0.001),
            _ => panic!("Expected FireCue"),
        }
    }

    #[test]
    fn parse_cue_go() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/go", &[], src).unwrap();
        assert!(matches!(event, TriggerEvent::GoNext));
    }

    #[test]
    fn parse_cue_previous() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/previous", &[], src).unwrap();
        assert!(matches!(event, TriggerEvent::GoPrevious));
    }

    #[test]
    fn parse_cue_current() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message("/cue/current", &[], src).unwrap();
        match event {
            TriggerEvent::QueryCurrent { reply_addr } => {
                assert_eq!(reply_addr, src);
            }
            _ => panic!("Expected QueryCurrent"),
        }
    }

    #[test]
    fn parse_macro_fire() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event =
            parse_trigger_message("/macro/fire", &[OscType::String("mute_all".into())], src)
                .unwrap();
        match event {
            TriggerEvent::MacroFire(name) => assert_eq!(name, "mute_all"),
            _ => panic!("Expected MacroFire"),
        }
    }

    #[test]
    fn parse_unknown_returns_none() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        assert!(parse_trigger_message("/unknown/path", &[], src).is_none());
    }

    // ─── Phase E: /snapshot/recall* ────────────────────────────────────

    #[test]
    fn parse_snapshot_recall_with_string_arg() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message(
            "/snapshot/recall",
            &[OscType::String("Verse 1".into())],
            src,
        )
        .unwrap();
        match event {
            TriggerEvent::SnapshotRecall {
                identifier,
                ignore_scope,
            } => {
                assert_eq!(identifier, "Verse 1");
                assert!(!ignore_scope);
            }
            _ => panic!("Expected SnapshotRecall"),
        }
    }

    #[test]
    fn parse_snapshot_recall_full_sets_ignore_scope_true() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message(
            "/snapshot/recall_full",
            &[OscType::String("Verse 1".into())],
            src,
        )
        .unwrap();
        match event {
            TriggerEvent::SnapshotRecall { ignore_scope, .. } => assert!(ignore_scope),
            _ => panic!("Expected SnapshotRecall"),
        }
    }

    #[test]
    fn parse_snapshot_recall_accepts_uuid_string() {
        // The parser doesn't validate UUID syntax — that's resolve_snapshot's
        // job. Any string passes through.
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        let event = parse_trigger_message(
            "/snapshot/recall",
            &[OscType::String(
                "9c0a1234-0000-0000-0000-000000000001".into(),
            )],
            src,
        )
        .unwrap();
        match event {
            TriggerEvent::SnapshotRecall { identifier, .. } => {
                assert_eq!(identifier, "9c0a1234-0000-0000-0000-000000000001");
            }
            _ => panic!("Expected SnapshotRecall"),
        }
    }

    #[test]
    fn parse_snapshot_recall_missing_arg_returns_none() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        assert!(parse_trigger_message("/snapshot/recall", &[], src).is_none());
    }

    #[test]
    fn parse_snapshot_recall_non_string_arg_returns_none() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        assert!(parse_trigger_message("/snapshot/recall", &[OscType::Int(42)], src).is_none());
    }

    #[test]
    fn parse_snapshot_recall_empty_string_returns_none() {
        let src: SocketAddr = "127.0.0.1:9000".parse().unwrap();
        assert!(
            parse_trigger_message("/snapshot/recall", &[OscType::String(String::new())], src,)
                .is_none()
        );
    }
}
